package br.com.system.gestaoConstrucaoCivil.enuns;

public enum PerfilUsuarioEnum {
	
	//MODULO ADMIN SISTEMA
	MODULO_ADMIN("Modulo administrador"),
	EMPRESA_CONTRATADA_CADASTRAR("Empresa contradata"),
	EMPRESA_CONTRATADA_ALTERAR("Empresa contradata"),
	EMPRESA_CONTRATADA_CONSULTAR("Empresa contradata"),
	
	//MODULO DE CADASTROS
	MODULO_CADASTROS("modulo de cadastros"),
	MODULO_CADASTROS_AREA_CADASTRAR("modulo de cadastros"),
	MODULO_CADASTROS_AREA_ALTERAR("modulo de cadastros"),
	MODULO_CADASTROS_AREA_CONSULTAR("modulo de cadastros"),
	
	MODULO_CADASTROS_FABRICANTE_CADASTRAR("modulo de cadastros"),
	MODULO_CADASTROS_FABRICANTE_ALTERAR("modulo de cadastros"),
	MODULO_CADASTROS_FABRICANTE_CONSULTAR("modulo de cadastros"),
	
	MODULO_CADASTROS_FORNECEDOR_CADASTRAR("modulo de cadastros"),
	MODULO_CADASTROS_FORNECEDOR_ALTERAR("modulo de cadastros"),
	MODULO_CADASTROS_FORNECEDOR_CONSULTAR("modulo de cadastros"),
	
	MODULO_CADASTROS_PRODUTO_CADASTRAR("modulo de cadastros"),
	MODULO_CADASTROS_PRODUTO_ALTERAR("modulo de cadastros"),
	MODULO_CADASTROS_PRODUTO_CONSULTAR("modulo de cadastros"),
	
	MODULO_CADASTROS_PRODUTO_CATEGORIA_CADASTRAR("modulo de cadastros"),
	MODULO_CADASTROS_PRODUTO_CATEGORIA_ALTERAR("modulo de cadastros"),
	MODULO_CADASTROS_PRODUTO_CATEGORIA_CONSULTAR("modulo de cadastros"),
	
	MODULO_CADASTROS_PRODUTO_TIPO_CADASTRAR("modulo de cadastros"),
	MODULO_CADASTROS_PRODUTO_TIPO_ALTERAR("modulo de cadastros"),
	MODULO_CADASTROS_PRODUTO_TIPO_CONSULTAR("modulo de cadastros"),
	
	//MODULO DE CHAMADOS
	
	MODULO_CHAMADO("modulo de cadastros"),
	MODULO_CHAMADO_INFORMATICA_USUARIO("modulo de cadastros"),
	MODULO_CHAMADO_INFORMATICA_SUPORTE("modulo de cadastros"),
	MODULO_CHAMADO_INFORMATICA_SUPORTE_RELATORIO("modulo de cadastros"),
	
	MODULO_CHAMADO_MANUTENCAO_USUARIO("modulo de cadastros"),
	MODULO_CHAMADO_MANUTENCAO_SUPORTE("modulo de cadastros"),
	MODULO_CHAMADO_MANUTENCAO_SUPORTE_RELATORIO("modulo de cadastros"),
	
	//MODULO COMPRAS
	
	MODULO_COMPRAS("modulo de cadastros"),
	MODULO_COMPRAS_CADASTRAR("modulo de cadastros"),
	MODULO_COMPRAS_ALTERAR("modulo de cadastros"),
	MODULO_COMPRAS_CONSULTAR("modulo de cadastros"),
	
	MODULO_COMPRAS_COTACAO_GERAR("modulo de cadastros"),
	MODULO_COMPRAS_COTACAO_CADASTRAR("modulo de cadastros"),
	MODULO_COMPRAS_COTACAO_ABERTO("modulo de cadastros"),
	MODULO_COMPRAS_COTACAO_VENCEDORES_CONSULTAR("modulo de cadastros"),
	MODULO_COMPRAS_COTACAO_CONCORRENTES_CONSULTAR("modulo de cadastros"),
	
	// MODULO ESTOQUE
	
	MODULO_ESTOQUE("modulo estoque"),
	MODULO_ESTOQUE_ENTRADA("ENTRADA"),
	MODULO_ESTOQUE_CONSULTA("ENTRADA"),
	MODULO_ESTOQUE_ALTERA_LIMITE("ROLE_MODULO_COMPRAS_ALTERA_LIMITE"),
	
	MODULO_REQUISICAO_CADASTRAR("ENTRADA"),
	MODULO_REQUISICAO_CONSULTA("ENTRADA"),	
	MODULO_REQUISICAO_CONSULTA_CASA("ENTRADA"),
	MODULO_REQUISICAO_CONSULTA_EDIFICIO("ENTRADA"),
	MODULO_REQUISICAO_CONSULTA_OUTROS("ENTRADA"),
	
	MODULO_ESTOQUE_TRANSFERENCIA_ENVIADAS("modulo estoque"),
	MODULO_ESTOQUE_TRANSFERENCIA_RECEBIDAS("modulo estoque"),
	MODULO_ESTOQUE_TRANSFERENCIA_CADASTRAR("modulo estoque"),
	MODULO_ESTOQUE_TRANSFERENCIA_CONSULTA_ENVIADAS("modulo estoque"),
	MODULO_ESTOQUE_TRANSFERENCIA_CONSULTA_RECEBIDAS("modulo estoque"),
	
	//MODULO GERENCIAMENTO
	
	MODULO_GERENCIAMENTO("MODULO GERENCIAMENTO"),
	MODULO_GERENCIAMENTO_EMPREENDIMENTO_CADASTRAR("MODULO GERENCIAMENTO"),
	MODULO_GERENCIAMENTO_EMPREENDIMENTO_CONSULTAR("MODULO GERENCIAMENTO"),
	MODULO_GERENCIAMENTO_EMPREENDIMENTO_ALTERAR("MODULO GERENCIAMENTO"),
	MODULO_GERENCIAMENTO_EMPREENDIMENTO_INFORMACOES("MODULO GERENCIAMENTO"),
	
	EMPREENDIMENTO_CONFIGURACAO_CADASTRAR("MODULO GERENCIAMENTO"),
	EMPREENDIMENTO_CONFIGURACAO_CONSULTAR("MODULO GERENCIAMENTO"),
	EMPREENDIMENTO_CONFIGURACAO_ALTERAR("MODULO GERENCIAMENTO"),
	
	USUARIO_CADASTRAR("MODULO GERENCIAMENTO"),
	USUARIO_EMPREENDIMENTO_CONSULTAR("MODULO GERENCIAMENTO"),
	USUARIO_EMPREENDIMENTO_ALTERAR("MODULO GERENCIAMENTO"),
	USUARIO_EMPREENDIMENTO_PERMISSSAO("MODULO GERENCIAMENTO"),
	
	USUARIO_PERMISSAO_CADASTRAR("MODULO GERENCIAMENTO"),
	USUARIO_PERMISSAO_EMPREENDIMENTO_CONSULTAR("MODULO GERENCIAMENTO"),
	USUARIO_PERMISSAO_EMPREENDIMENTO_ALTERAR("MODULO GERENCIAMENTO"),
	
	//MODULO RECURSOS HUMANOS
	
	MODULO_RECURSOS_HUMANOS("MODULO RH"),
	MODULO_RECURSOS_HUMANOS_CARGO_CADASTRAR("MODULO RH"),
	MODULO_RECURSOS_HUMANOS_CARGO_ALTERAR("MODULO RH"),
	MODULO_RECURSOS_HUMANOS_CARGO_CONSULTAR("MODULO RH"),
	
	MODULO_RECURSOS_HUMANOS_FUNCIONARIO_CADASTRAR("MODULO RH"),
	MODULO_RECURSOS_HUMANOS_FUNCIONARIO_ALTERAR("MODULO RH"),
	MODULO_RECURSOS_HUMANOS_FUNCIONARIO_CONSULTAR("MODULO RH"),
	
	
	//MODULO SERVICOS
	MODULO_SERVICOS(" MODULO SERVIÇOS"),
	PACOTES_CADASTRAR(" MODULO SERVIÇOS"),
	PACOTES_ALTERAR(" MODULO SERVIÇOS"),
	PACOTES_CONSULTAR(" MODULO SERVIÇOS"),
	
	PRESTADORA_SERVICOS_CADASTRAR(" MODULO SERVIÇOS"),
	PRESTADORA_SERVICOS_ALTERAR(" MODULO SERVIÇOS"),
	PRESTADORA_SERVICOS_CONSULTAR(" MODULO SERVIÇOS"),
	
	VINCULAR_CADASTRAR(" MODULO SERVIÇOS"),
	VINCULAR_CONSULTAR(" MODULO SERVIÇOS"),
	VINCULAR_CONSULTAR_CASA(" MODULO SERVIÇOS"),
	VINCULAR_CONSULTAR_EDIFICIO(" MODULO SERVIÇOS"),
	VINCULAR_CONSULTAR_EDIFICACOES_COMUNITARIA(" MODULO SERVIÇOS");
	
	
	
	 private String descricao;
	
	PerfilUsuarioEnum(String descricao) {
        this.descricao = descricao;
    }

	public String getDescricao() {
		return descricao;
	}

	
	

}
