package br.com.system.gestaoConstrucaoCivil.enuns;

public enum TipoModulo {

	MODULO_ADMIN,
	MODULO_CADASTROS,
	MODULO_CHAMADO,
	MODULO_COMPRAS,	
	MODULO_ESTOQUE,
	MODULO_GERENCIAMENTO,
	MODULO_RECURSOS_HUMANOS,
	MODULO_SERVICOS;
	
}
